"""
Django settings for flori_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os

from dotenv import load_dotenv

load_dotenv()

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!os88t4yi7bkm*_gz95irdv9#sk^*84@fvw_5i_!^!y@le&pdj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Lista de apps Django ativos neste projeto. Cada string é o nome de um
# pacote Python que o Django carrega ao iniciar (models, admin, etc.).
INSTALLED_APPS = [
    'django.contrib.admin',        
    'django.contrib.auth',         
    'django.contrib.contenttypes', 
    'django.contrib.sessions',     
    'django.contrib.messages',     
    'django.contrib.staticfiles',  
    'corsheaders',                 
    'users'                        
]

# Lista ordenada de middlewares: cada requisição passa por eles de cima para
# baixo (e a resposta passa de baixo para cima na volta).
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',            
    'django.middleware.security.SecurityMiddleware',    
    'django.contrib.sessions.middleware.SessionMiddleware',  
    'django.middleware.common.CommonMiddleware',         
    'django.middleware.csrf.CsrfViewMiddleware',          
    'django.contrib.auth.middleware.AuthenticationMiddleware',  
    'django.contrib.messages.middleware.MessageMiddleware',      
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    
]
# Libera requisições de QUALQUER origem (front-end em outra porta/domínio, ex: file:// ou 127.0.0.1:5500).
# Ver uso do fetch() em frontend/cadastro.js chamando http://127.0.0.1:8000.
CORS_ALLOW_ALL_ORIGINS = True
# Indica qual módulo Python contém a tabela de rotas raiz do projeto
# (aponta para backend/flori_backend/urls.py).
ROOT_URLCONF = 'flori_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flori_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

BREVO_API_KEY = os.getenv('BREVO_API_KEY', '').strip()
BREVO_REMETENTE_EMAIL = os.getenv('BREVO_REMETENTE_EMAIL', '').strip()
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://127.0.0.1:5500').rstrip('/')
# Projeto Firebase do login com Google. O back-end só aceita ID tokens emitidos
# para ESTE projeto (campo 'aud' do token) — ver users/services.py -> LoginGoogle.
FIREBASE_PROJECT_ID = os.getenv('FIREBASE_PROJECT_ID', 'flori-1742a').strip()

# Atalho de desenvolvimento: com DB_ENGINE=sqlite no .env, sobe sem precisar de um
# MySQL local. O banco oficial do projeto continua sendo o MySQL do schema_users.sql.
if os.getenv('DB_ENGINE') == 'sqlite':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
