"""
Django settings for flori_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
# os: usado para ler variáveis de ambiente (os.getenv) como as credenciais do banco.
import os
# load_dotenv: função da lib python-dotenv que lê o arquivo .env na raiz do
#              projeto e injeta seu conteúdo em os.environ.
from dotenv import load_dotenv
# Chamada de função (não é declaração, é execução imediata ao carregar o módulo):
# carrega o .env ANTES de qualquer os.getenv() ser usado mais abaixo neste arquivo.
load_dotenv()
# Path: classe da lib padrão pathlib, usada para montar caminhos de arquivo
#       de forma independente de sistema operacional (Windows/Linux/Mac).
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR é uma instância de Path apontando para a pasta raiz do projeto
# (duas pastas acima deste arquivo: flori_backend/settings.py -> flori_backend/ -> backend/).
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!os88t4yi7bkm*_gz95irdv9#sk^*84@fvw_5i_!^!y@le&pdj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Lista de apps Django ativos neste projeto. Cada string é o nome de um
# pacote Python que o Django carrega ao iniciar (models, admin, etc.).
INSTALLED_APPS = [
    'django.contrib.admin',        # painel administrativo (/admin/)
    'django.contrib.auth',         # sistema de autenticação/usuários do Django (não usado por Usuario, que é model próprio)
    'django.contrib.contenttypes', # framework de tipos de conteúdo, dependência de auth/admin
    'django.contrib.sessions',     # suporte a sessões (cookies de sessão)
    'django.contrib.messages',     # framework de mensagens flash entre requisições
    'django.contrib.staticfiles',  # coleta/serve arquivos estáticos (CSS/JS/imagens)
    'corsheaders',                 # lib externa (django-cors-headers) que libera requisições do front-end (outra origem)
    'users'                        # app próprio do projeto (backend/users/), com UsersConfig definido em apps.py
]

# Lista ordenada de middlewares: cada requisição passa por eles de cima para
# baixo (e a resposta passa de baixo para cima na volta).
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',            # adiciona os headers de CORS nas respostas
    'django.middleware.security.SecurityMiddleware',    # cabeçalhos de segurança (HSTS, etc.)
    'django.contrib.sessions.middleware.SessionMiddleware',  # habilita request.session
    'django.middleware.common.CommonMiddleware',         # ajustes gerais (ex: normalização de URL)
    'django.middleware.csrf.CsrfViewMiddleware',          # proteção CSRF (desligada só na view de cadastro, via csrf_exempt)
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # habilita request.user
    'django.contrib.messages.middleware.MessageMiddleware',      # habilita o framework de mensagens
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    # bloqueia embutir o site em <iframe> de outro domínio
]
# Libera requisições de QUALQUER origem (front-end em outra porta/domínio, ex: file:// ou 127.0.0.1:5500).
# Ver uso do fetch() em frontend/cadastro.js chamando http://127.0.0.1:8000.
CORS_ALLOW_ALL_ORIGINS = True
# Indica qual módulo Python contém a tabela de rotas raiz do projeto
# (aponta para backend/flori_backend/urls.py).
ROOT_URLCONF = 'flori_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flori_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Dicionário de configuração de conexão com o banco. 'default' é o alias
# usado pelo Django sempre que nenhum banco é especificado explicitamente
# (é o banco onde Usuario e Consentimento, de models.py, são persistidos).
# Os valores vêm de variáveis de ambiente (lidas do .env por load_dotenv() acima).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Atalho de desenvolvimento: com DB_ENGINE=sqlite no .env, sobe sem precisar de um
# MySQL local. O banco oficial do projeto continua sendo o MySQL do schema_users.sql.
if os.getenv('DB_ENGINE') == 'sqlite':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
