# Generated by Django 5.2.17 on 2026-09-21 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=50)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(editable=False, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='users.usuario')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('termos_uso', 'Termos de uso'), ('politica_privacidade', 'Política de privacidade')], max_length=30)),
                ('versao_documento', models.CharField(max_length=20)),
                ('aceito', models.BooleanField()),
                ('data_consentimento', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos', to='users.usuario')),
            ],
            options={
                'db_table': 'consentimentos',
                'indexes': [models.Index(fields=['usuario', 'tipo', '-data_consentimento'], name='consentimen_usuario_8c9dd9_idx')],
            },
        ),
    ]
