# Generated by Django 6.1.1 on 2026-09-23 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_logatividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('cadastro', 'Cadastro realizado'), ('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('redefinicao_senha_solicitada', 'Redefinição de senha solicitada')], max_length=30),
        ),
        migrations.CreateModel(
            name='SolicitacaoRedefinicaoSenha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_redefinicao_senha', to='users.usuario')),
            ],
            options={
                'db_table': 'solicitacoes_redefinicao_senha',
                'indexes': [models.Index(fields=['email', '-criado_em'], name='solicitacoe_email_cb1864_idx')],
            },
        ),
    ]
