# Generated by Django 6.1.1 on 2026-09-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_redefinicao_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('cadastro', 'Cadastro realizado'), ('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('redefinicao_senha_solicitada', 'Redefinição de senha solicitada'), ('senha_redefinida', 'Senha redefinida')], max_length=30),
        ),
    ]
