# Generated by Django 6.1.1 on 2026-09-24 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_log_senha_redefinida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('cadastro', 'Cadastro realizado'), ('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('redefinicao_senha_solicitada', 'Redefinição de senha solicitada'), ('senha_redefinida', 'Senha redefinida'), ('codigo_2fa_enviado', 'Código de verificação enviado'), ('codigo_2fa_invalido', 'Código de verificação inválido')], max_length=30),
        ),
        migrations.CreateModel(
            name='CodigoAutenticacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desafio_hash', models.CharField(max_length=64, unique=True)),
                ('codigo_hash', models.CharField(max_length=255)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_autenticacao', to='users.usuario')),
            ],
            options={
                'db_table': 'codigos_autenticacao',
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='codigos_aut_usuario_17802f_idx')],
            },
        ),
    ]
