# Generated by Django 6.1.1 on 2026-09-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_log_login_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logatividade',
            name='acao',
            field=models.CharField(choices=[('cadastro', 'Cadastro realizado'), ('login_sucesso', 'Login com sucesso'), ('login_falha', 'Tentativa de login falhou'), ('redefinicao_senha_solicitada', 'Redefinição de senha solicitada'), ('senha_redefinida', 'Senha redefinida'), ('codigo_2fa_enviado', 'Código de verificação enviado'), ('codigo_2fa_invalido', 'Código de verificação inválido'), ('login_google', 'Login com Google'), ('logout', 'Saiu da conta')], max_length=30),
        ),
    ]
